### PR TITLE
Improved URL parsing

### PR DESCRIPTION
**Pull request by patheticcockroach**
Hi,
I made some changes to the way URLs are handled so that leading whitespace and trailing HTML tag aren't included into the "href" attribute. The previous version created issues when using nl2br() before or after processing by tweetParser.
(my first pull request, hope I got this right ^^)

### CODE REVIEW

**Comment by VincentLoy** [comment]
Hey thanks patheticcockroach :)

**Comment by Xowap** [comment]
Well instead you can use a non-capturing group like `(?:^|\s)((f|ht)tps?:\/\/([^ \t\r\n<]*[^ \t\r\n\<)*_,\.]))` which I believe removes the need for the p1/p2 hack

**Comment by Xowap** [comment]
My bad, I mistook that for lookbehinds, which are not supported in JS.

**Comment by patheticcockroach** [comment]
Indeed my first try was to use a non-capturing group but it didn't help ;)

**Pull request merged**
